export const COLLAPSE_CHANGE_LEFT = 'COLLAPSE_CHANGE_LEFT';
export const COLLAPSE_CHANGE_RIGHT = 'COLLAPSE_CHANGE_RIGHT';
export const TOGGLE_ALL = 'TOGGLE_ALL';

export const CHANGE_TIME_ZONE = 'CHANGE_TIME_ZONE';

export const CHANGE_LANG = 'CHANGE_LANG';
